export const LEADHEADERS = [
  "#",
  "Client Name",
  "Brand Mark",
  "Serial No",
  "Phone No",
  "Email",
  "Last Activity",
  "Signup Date",
  "Department/brand",
  "Paid Status",
  // "Last Comment",
  // "Agent",
  "Action",
];