// app/head.tsx
export default function Head() {
    return (
      <>
        <meta name="google-adsense-account" content="ca-pub-6648219347495285" />
        <title>Auction</title>
        <meta name="description" content="Generated by create next app" />
      </>
    );
  }
  